# https://github.com/niri-wm/niri/pull/3483
include ~/.cache/wal/colors-kitty.conf

font_family                 JetBrainsMono Nerd Font
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
font_size                   17.0

remember_window_size        no
confirm_os_window_close     0
enable_audio_bell           no
cursor_blink_interval       0
cursor_trail                80
cursor_trail_decay          0.08 0.25
cursor_trail_start_threshold 3

scrollback_lines            5000
wheel_scroll_min_lines      1

window_padding_width        12
window_margin_width         6
placement_strategy          center
hide_window_decorations     yes

background_opacity          0.82
dynamic_background_opacity  yes
background_blur             16
background_tint 0.15

inactive_text_alpha         0.85

map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard
