source = colors.conf

background {
    monitor =
    path = screenshot
    blur_size = 5
    blur_passes = 4
    noise = 0.015
    contrast = 0.95
    brightness = 0.75
    vibrancy = 0.18
    vibrancy_darkness = 0.05
}

label {
    monitor =
    text = <b>$TIME</b>
    color = $on_surface
    font_size = 100
    font_family = Adwaita Sans
    shadow_passes = 4
    shadow_size = 6
    shadow_color = $shadow
    position = 0, 280
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %B %d"
    color = $on_surface_variant
    font_size = 18
    font_family = Adwaita Sans
    position = 0, 190
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 56
    outline_thickness = 1
    dots_size = 0.15
    dots_spacing = 0.4
    dots_center = true
    inner_color = $surface_container
    outer_color = $outline
    font_color = $on_surface
    font_family = Adwaita Sans
    check_color = $primary
    fail_color = $error
    capslock_color = $error
    bothlock_color = $error
    placeholder_text = <i>Password</i>
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fade_on_empty = true
    fade_timeout = 1200
    rounding = 20
    position = 0, 100
    halign = center
    valign = bottom
}

general {
    hide_cursor = true
    ignore_empty_input = true
    fail_timeout = 1500
}

animations {
    enabled = true
    animation = fadeIn, 1, 1, default
    animation = fadeOut, 1, 1, default
}
