SPACE        cycle pause; script-binding uosc/flash-pause-indicator
RIGHT        seek 5; script-binding uosc/flash-timeline
LEFT         seek -5; script-binding uosc/flash-timeline
Shift+RIGHT  no-osd seek 1 exact; script-binding uosc/flash-timeline
Shift+LEFT   no-osd seek -1 exact; script-binding uosc/flash-timeline
[            no-osd add speed -0.05; script-binding uosc/flash-speed
]            no-osd add speed 0.05; script-binding uosc/flash-speed
BS           no-osd set speed 1; script-binding uosc/flash-speed
ENTER        cycle fullscreen
ESC          set fullscreen no; set window-maximized no
q            quit
Shift+q      quit_watch_later

Tab          script-binding uosc/toggle-ui
Shift+m      script-binding uosc/menu
p            script-binding uosc/playlist
c            script-binding uosc/chapters

o            script-binding uosc/open-file
Shift+o      script-binding uosc/load-subtitles
w            script-binding uosc/show-in-directory
>            script-binding uosc/next
<            script-binding uosc/prev
L            cycle-values loop-file inf no; show-text "Loop: ${loop-file}"
l            ab-loop

Alt+t        cycle ontop
Alt+1        set window-scale 0.5
Alt+2        set window-scale 1.0
Alt+3        set window-scale 2.0

D            cycle deband
d            cycle deinterlace
-            cycle video
=            cycle audio
j            cycle sub
Y            script-binding uosc/subtitles
v            cycle sub-visibility
u            cycle-values sub-ass-override "force" "yes"
Shift+g      add sub-scale 0.05
Shift+f      add sub-scale -0.05
z            add sub-delay -0.042
x            add sub-delay 0.042
r            add sub-pos -1
t            add sub-pos 1
Shift+BS     set sub-pos 100; set sub-scale 1.0; set sub-delay 0; show-text "Subtitles reset"

m            no-osd cycle mute; script-binding uosc/flash-volume
0            no-osd add volume 2; script-binding uosc/flash-volume
9            no-osd add volume -2; script-binding uosc/flash-volume

s            async screenshot
Shift+s      async screenshot video
Ctrl+s       async screenshot window
?            script-binding uosc/keybinds
i            script-binding stats/display-stats
`            script-binding commands/open
Ctrl+w       script-binding uosc/open-config-directory

MBTN_LEFT        ignore
MBTN_LEFT_DBL    cycle fullscreen
MBTN_MID         cycle pause; script-binding uosc/flash-pause-indicator
MBTN_RIGHT       script-binding uosc/menu-blurred
MBTN_FORWARD     script-binding uosc/next
MBTN_BACK        script-binding uosc/prev
WHEEL_UP         add volume 2; script-binding uosc/flash-volume
WHEEL_DOWN       add volume -2; script-binding uosc/flash-volume
WHEEL_LEFT       seek -5; script-binding uosc/flash-timeline
WHEEL_RIGHT      seek 5; script-binding uosc/flash-timeline
