include="~~/profiles.conf"

fullscreen=yes
keep-open=yes
watch-later-options=start,sid

hr-seek=yes
input-default-bindings=no
audio-file-auto=fuzzy
sub-auto=fuzzy
autocreate-playlist=filter
directory-filter-types=video,audio

profile=HighQuality
vo=gpu-next
hwdec=no
gpu-context=wayland
tone-mapping=bt.2446a

ytdl=no

osc=no
osd-bar=no
border=no
background=color
cursor-autohide-fs-only=yes
cursor-autohide=1200
osd-font="FiraCode Nerd Font"
osd-duration=1300
osd-outline-size=1

volume-max=150

alang=jp,jpn,en,eng
slang=en,eng,jp,jpn,und
demuxer-mkv-subtitle-preroll=yes
sub-file-paths=ass;srt;sub;subs;subtitles;Subs
sub-font="Netflix Sans Med"
sub-font-size=36
sub-color="#FFFFFFFF"
sub-border-color="#FF000000"
sub-border-size=1.8
sub-shadow-color=0.0/0.0/0.0/0.65
sub-shadow-offset=0.7
sub-spacing=0.6
sub-bold=yes
sub-blur=0.25
sub-use-margins=no

deband=no

screenshot-format=png
screenshot-png-compression=4
screenshot-dir="~/Pictures/mpv"
