#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

[options]
PgpFetch
Devel
DevelSuffixes = -git -always
Provides
RemoveMake
SudoLoop
CombinedUpgrade
UpgradeMenu
NewsOnUpgrade
SortBy = votes
BottomUp
