timeline_style=bar
timeline_size=24
timeline_border=0
timeline_cache=yes

progress_size=2
progress_line_width=12

controls=menu,gap,<video,audio>subtitles,<has_many_audio>audio,<has_many_video>video,<has_chapter>chapters,space,<video,audio>speed,toggle:volume_off:mute?Mute,space,prev,items,next,fullscreen
controls_size=28
controls_margin=6
controls_spacing=1

volume=left
volume_size=30
volume_persistency=audio,video
volume_step=2

speed_step=0.05

menu_item_height=32
menu_min_width=220
menu_padding=3

top_bar_size=36
top_bar_controls=no
top_bar_flash_on=

scale=0.95
scale_fullscreen=0.95
font_scale=0.95
text_border=1
border_radius=2
color=foreground=f2f2f2,foreground_text=101010,background=101010,background_text=f2f2f2,curtain=000000,success=cfcfcf,error=8c8c8c,match=bdbdbd
opacity=controls=0.95,curtain=0.72,menu=0.96,timeline=0.95
animation_duration=80
flash_duration=1200
proximity_in=24
proximity_out=80
autohide=yes

load_types=video,audio
chapter_ranges=
languages=en
